Dish_Helper/Dish_Helper/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path


from Dish_Helper_app.views import MainPageView, AddMealView, AddTypeOfMealView, AddIngredientView, \
    AddIngredientMeasurementView, ProfileRegisterView, MealDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='base'),
    path('login/', auth_views.LoginView.as_view(template_name='templates/Dish_Helper_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='templates/Dish_Helper_app/logout.html'), name='logout'),
    path('register/', ProfileRegisterView.as_view(), name='register'),
    path('add_meal/', AddMealView.as_view(template_name='templates/Dish_Helper_app/meal_form.html'), name='add_meal'),
    path('add_type/', AddTypeOfMealView.as_view(template_name='templates/Dish_Helper_app/typeofmeal_form.html'), name='add_type'),
    path('add_ingredient/', AddIngredientView.as_view(template_name='templates/Dish_Helper_app/ingredient_form.html'), name='add_ingredient'),
    path('add_measurement/', AddIngredientMeasurementView.as_view(template_name='templates/Dish_Helper_app/ingredientmeasurement_form.html'), name='add_measurement'),
    path('mealdetail/<int:id>/', MealDetailView.as_view(), name='mealdetail'),
]

Dish_Helper/Dish_Helper_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user_name = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user_name


class Meal(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True)
    recipe = models.TextField(null=True)
    total_time = models.PositiveIntegerField(null=True)
    servings = models.PositiveSmallIntegerField(null=True)
    measurement = models.ManyToManyField('Ingredient', through='IngredientMeasurement')

    def __str__(self):
        return self.name


class TypeOfMeal(models.Model):

    CHOICES = [
        (0, 'breakfast & brunch'),
        (1, 'lunch'),
        (2, 'dinner'),
        (3, 'appetizers & snacks'),
        (4, 'cocktails'),
    ]

    type_of_meal = models.IntegerField(choices=CHOICES)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.type_of_meal


class Ingredient(models.Model):
    name = models.CharField(max_length=128, unique=True)
    calories = models.PositiveSmallIntegerField(null=True)
    fat = models.PositiveSmallIntegerField(null=True)
    carbs = models.PositiveSmallIntegerField(null=True)
    protein = models.PositiveSmallIntegerField(null=True)

    def __str__(self):
        return self.name


class IngredientMeasurement(models.Model):
    weight = models.PositiveSmallIntegerField(null=True)
    ingredient_id = models.ForeignKey(Ingredient, on_delete=models.CASCADE, null=True)
    meal_id = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.weight

Dish_Helper/Dish_Helper_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=128)
    last_name = forms.CharField(max_length=256)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

Dish_Helper/Dish_Helper_app/views.py
from urllib import request
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, FormView
from .forms import UserRegisterForm
from .models import Meal, TypeOfMeal, Ingredient, IngredientMeasurement


class ProfileLoginView(FormView):
    """
    View for handling user login via a form submission.
    This view displays a form where users can enter their username and password.
    Upon form submission, the view attempts to authenticate the user with Django's authentication system.
    If authentication is successful, the user is logged in and redirected to the 'base' URL.
    If authentication fails, an error message is displayed and the user is prompted to try again.

    Attributes:
        template_name (str): The path to the template for this view.
        success_url (str): The URL to redirect to upon successful form submission.

    Methods:
        form_valid: Handle a valid form submission.
    """
    template_name = 'templates/Dish_Helper_app/profile_form.html'
    success_url = 'base'

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            login(self, request, user)
            messages.success(self.request, "You've been logged in")
        return super().form_valid(form)


class ProfileRegisterView(View):
    """
    View for handling user registration via a form submission.
    This view displays a form where users can enter their desired username, email address, and password.
    Upon form submission, the view attempts to validate the form data.
    If validation is successful, the view creates a new user account and redirects the user to the 'base' URL.
    If validation fails, error messages are displayed and the user is prompted to try again.
    """
    def post(self, request):
        """
        Handle a POST request to register a new user account.

        :param request: The HTTP request object.
        :return: A redirect response to the home page if registration is successful,
                 or a redirect response to the registration page if registration fails.
        """
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created! You are now able to log in.')
            return redirect('base')
        else:
            error_messages = list(form.errors.values())
            for message in error_messages:
                messages.error(request, message)
            return redirect('register')

    def get(self, request):
        """
        Display the user registration form.
        :param request: the HTTP request object.
        :return: the HTTP response object with the rendered register.html template.
        """
        form = UserRegisterForm()
        context = {'form': form}
        return render(request, 'templates/Dish_Helper_app/register.html', context)


class MainPageView(View):
    """
    View for the home page of the Dish Helper app.
    This view has two main functionalities: displaying a random meal and allowing users to filter meals by ingredient.
    """

    def get_random_meal(self):
        """
        Get a random meal from the database.

        :return: A randomly selected meal.
        """
        return Meal.objects.order_by('?').first()

    def get(self, request):
        """
        Handle GET requests to the home page.

        :param request: The HTTP request object.
        :return: The rendered HTML page containing the home page.
        """
        meals = list(Meal.objects.all())
        ingredients = Ingredient.objects.all()
        random_meal = self.get_random_meal()
        return render(
            request,
            'templates/Dish_Helper_app/home_page.html',
            context={'meals': meals, 'random_meal': random_meal, 'ingredients': ingredients}
        )

    def post(self, request):
        """
        Handle POST requests to filter meals by ingredient.

        :param request: The HTTP request object.
        :return: The rendered HTML page containing the filtered meals.
        """
        ingredient_id = request.POST.get('ingredient')
        ingredient = Ingredient.objects.get(pk=ingredient_id)
        meals = Meal.objects.filter(ingredientmeasurement__ingredient_id=ingredient)
        return render(
            request,
            'templates/Dish_Helper_app/home_page.html',
            context={'meals': meals, 'ingredient': ingredient}
        )


class MealDetailView(LoginRequiredMixin, View):
    """
    View for displaying details of a Meal object.
    This view displays the name, type, ingredients, and measurements for a single Meal object.
    Only logged-in users can access this page.
    """
    def get(self, request, id):
        """
        Handle GET requests to the Meal Detail page.

        :param request: The HTTP request object.
        :param id: The ID of the meal to view.
        :return: The rendered HTML page containing the details of the meal.
        """
        meal_id = int(id)
        meal = get_object_or_404(Meal, id=meal_id)
        type = TypeOfMeal.objects.filter(meal=meal).first()
        ingredients = Ingredient.objects.filter(meal=meal)
        measure = IngredientMeasurement.objects.filter(meal_id=meal)
        context = {
            'meal': meal,
            'type': type,
            'ingredients': ingredients,
            'measure': measure
        }
        return render(request, 'templates/Dish_Helper_app/meal_detail.html', context)


class AddMealView(LoginRequiredMixin, CreateView):
    """
    View for adding a new Meal object via a form submission.
    This view allows authenticated users to create new Meal objects by submitting a form with the required data.
    The form includes fields for the meal's name, description, recipe, total time, number of servings, and measurement.

    Attributes:
        model (Meal): The model class for creating new Meal objects.
        fields (list of str): The list of fields from the Meal model that should be included in the form.
        success_url (str): The URL to redirect to after a successful form submission.
        login_url (str): The URL to redirect to if a user attempts to access this view while not authenticated.

    Methods:
        form_valid(form): Handle a valid form submission.
    """
    model = Meal
    fields = ['name', 'description', 'recipe', 'total_time', 'servings', 'measurement']
    success_url = reverse_lazy('base')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Meal was added successfully.')
        return response


# View where authenticated user can add type of meal
class AddTypeOfMealView(LoginRequiredMixin, CreateView):
    """
    View for adding a new TypeOfMeal object via a form submission.
    This view allows authenticated users to create new TypeOfMeal objects by submitting a form with the required data.
    The form includes fields for the TypeOfMeal type_of_meal and meal.

    Attributes:
        model (TypeOfMeal): The model class for creating new TypeOfMeal objects.
        fields (list of str): The list of fields from the TypeOfMeal model that should be included in the form.
        success_url (str): The URL to redirect to after a successful form submission.
        login_url (str): The URL to redirect to if a user attempts to access this view while not authenticated.

    Methods:
        form_valid(form): Handle a valid form submission.
    """
    model = TypeOfMeal
    fields = ['type_of_meal', 'meal']
    success_url = reverse_lazy('base')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Type of meal was added successfully.')
        return response


# View where authenticated user can add ingredient
class AddIngredientView(LoginRequiredMixin, CreateView):
    """
    View for adding a new Ingredient object via a form submission.
    This view allows authenticated users to create new Ingredient objects by submitting a form with the required data.
    The form includes fields for the Ingredient name, calories, fat, carbs and protein.

    Attributes:
        model (Ingredient): The model class for creating new Ingredient objects.
        fields (list of str): The list of fields from the Ingredient model that should be included in the form.
        success_url (str): The URL to redirect to after a successful form submission.
        login_url (str): The URL to redirect to if a user attempts to access this view while not authenticated.

    Methods:
        form_valid(form): Handle a valid form submission.
    """
    model = Ingredient
    fields = ['name', 'calories', 'fat', 'carbs', 'protein']
    success_url = reverse_lazy('base')
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Ingredient was added successfully.')
        return response


# View where authenticated user can add ingredient measurement
class AddIngredientMeasurementView(LoginRequiredMixin, CreateView):
    """
    View for adding a new IngredientMeasurement object via a form submission.
    This view allows authenticated users to create new IngredientMeasurement objects by submitting a form with the
    required data.
    The form includes fields for the IngredientMeasurement weight, ingredient_id and meal_id.

    Attributes:
        model (IngredientMeasurement): The model class for creating new Ingredient objects.

Dish_Helper/templates/Dish_Helper_app/addingredientmeasurement_form.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}

    <form method="post">
    {% csrf_token %}
    {{ measurement_form.as_p }}
    <input type="submit" value="SAVE">
    </form>

{% endblock %}

Dish_Helper/templates/Dish_Helper_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dish Helper</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

{% include 'templates/Dish_Helper_app/navbar.html' %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" style="color: red"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<div class="container">
    {% block content %}
    {%  endblock %}
</div>
</body>
</html>

Dish_Helper/templates/Dish_Helper_app/create_meal.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}

    <form method="POST" action="">
    {% csrf_token %}
    {{ meal_form }}
    <input type="submit" value="Create Meal">
    </form>

{% endblock %}

Dish_Helper/templates/Dish_Helper_app/home_page.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}
    <h3>Here we are!</h3><br>
    	<h4>This page will help you prepare a meal with the ingredients you have at home.<br>
    	Let me help you!<br>
    	Choose the ingredients you have from the list of ingredients, and we will suggest a dish that you can prepare with them.<br>
    	Enjoy your meal!</h4><br><br>

    {% if user.is_authenticated %}
        <form method="post">
	{% csrf_token %}
	<label for="ingredient">Select an ingredient:</label>
	    <select name="ingredient" id="ingredient">
		{% for ingredient in ingredients %}
		    <option value="{{ ingredient.id }}">{{ ingredient.name }}</option>
		{% endfor %}
	    </select><br><br>
        <input type="submit" value="Search"><br><br>
        </form>

        {% if ingredient %}
	<h2>Meals that contain {{ ingredient.name }}:</h2>
	    <ul>{% if meals %}
	            {% for meal in meals %}
			<li><h3>Name: {{ meal.name }}</h3>
			    <p>Description: {{ meal.description }}</p>
                            <a href='mealdetail/{{ meal.id }}/'>Meal details</a>
			</li></ul>
		    {% endfor %}
		{% else %}
		    <p>No meals found.</p>
	    {% endif %}
	{% endif %}
        <br><br><br><br>
    {% else %}
        <a href="{% url 'login' %}">Please Login</a><br><br><br><br>
    {% endif %}

    <h4>Below you will find a sample meal from our website :)</h4><br>
    	<p>Name: {{ random_meal.name }}</p>
    	<p>Description: {{ random_meal.description }}</p>

    {% if user.is_authenticated %}
        <a href='mealdetail/{{ random_meal.id }}/'>Meal details</a><br><br>
    {% else %}
        <h4>You need to be logged in, to see Meal details.</h4>
            <a href="{% url 'login' %}">---> Login</a><br>
            <a href="{% url 'register' %}">---> Register</a><br>
    {% endif %}

{% endblock %}

Dish_Helper/templates/Dish_Helper_app/ingredient_form.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SAVE">
    </form>

{% endblock %}

Dish_Helper/templates/Dish_Helper_app/ingredientmeasurement_form.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SAVE">
    </form>

{% endblock %}

Dish_Helper/templates/Dish_Helper_app/login.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}
    <h3>login</h3>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>{{ field.label }}: {{ field }}</p>
        {% endfor %}
        <input type="submit" value="login">
    </form>
    <br><br><br>
    <p>Don't have an account? <a href="{% url 'register' %}">Signup here</a></p>
{% endblock %}

Dish_Helper/templates/Dish_Helper_app/logout.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}
    <br>
    <div class="alert alert-success" role="alert">
        <h2 style="text-align: center;">Logged out!</h2>
    </div>

    <h3>Login again?</h3>
    <a href="{% url 'login' %}">---> Login</a><br>
    <a href="{% url 'base' %}"><--- Or go back to home.</a>
{% endblock %}

Dish_Helper/templates/Dish_Helper_app/meal_detail.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}
    <h3>Name: {{ meal.name }}</h3>
        <p><b>Description:</b> {{ meal.description }}</p>
        <p><b>Recipe:</b> {{ meal.recipe }}</p>
        <p><b>Total time:</b> {{ meal.total_time }}</p>
        <p><b>Servings:</b> {{ meal.servings }}</p>
        <p><b>Type of meal:</b> {{ type.get_type_of_meal_display }}</p>
    <h4>Ingredients:</h4>
    <ul>
        {% for ingredient in ingredients %}
            <li>{{ ingredient.name }} -
                {% for measurement in measure %}
                     {{ measurement.weight }}</li>
                {% endfor %}
        {% endfor %}
    </ul>
{% endblock %}

Dish_Helper/templates/Dish_Helper_app/meal_form.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SAVE">
    </form>

{% endblock %}

Dish_Helper/templates/Dish_Helper_app/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'base' %}">Home</a>
        </li>
          {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
              </li>
          {% else %}
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Connect
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'register' %}">Signup</a></li>
                </ul>
              </div>
          {% endif %}
          {% if user.is_authenticated %}
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Creator
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'add_meal' %}">Create meal</a></li>
                    <li><a class="dropdown-item" href="{% url 'add_type' %}">Add type</a></li>
                    <li><a class="dropdown-item" href="{% url 'add_ingredient' %}">Add ingredient</a></li>
                    <li><a class="dropdown-item" href="{% url 'add_measurement' %}">Add measurement</a></li>
                </ul>
              </div>
          {% else %}
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>

Dish_Helper/templates/Dish_Helper_app/profile_form.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}
    <h2>Login</h2>
    {% if error_msg %}
        <p class="error">{{ error_msg }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required autofocus>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <div class="form-group">
            <label for="remember_me">Remember me:</label>
            <input type="checkbox" id="remember_me" name="remember_me">
        </div>
        <button type="submit">Login</button>
    </form>
{% endblock %}

Dish_Helper/templates/Dish_Helper_app/register.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}
    <h3>Register here</h3>
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div>
            <p>{{ field.label }}: {{ field }}</p>
            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>
    {% endfor %}
    <input type="submit" value="SAVE">
    </form>

{% endblock %}

Dish_Helper/templates/Dish_Helper_app/typeofmeal_form.html
{% extends 'templates/Dish_Helper_app/base.html' %}

{% block content %}

    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SAVE">
    </form>

{% endblock %}